# Generated by Django 5.2.8 on 2025-11-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_challenge_challengeattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='challengeattempt',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='challengeattempt',
            name='last_attempt',
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='challenge_thumbs/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='xp_reward',
            field=models.IntegerField(default=50),
        ),
    ]
