# Generated by Django 5.2.8 on 2025-11-10 13:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_challenge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 10, 13, 52, 55, 635362, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='time_spent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
