# Generated by Django 5.2.8 on 2025-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_challenge_created_at_challengeattempt_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeattempt',
            options={'ordering': ['-solved_at', '-started_at']},
        ),
        migrations.RenameField(
            model_name='challengeattempt',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
