# Generated by Django 5.2.8 on 2025-11-10 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_course_options_certificate_downloadable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topiccontent',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='topiccontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('quiz', 'Quiz')], default='text', max_length=20),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='short_description',
        ),
    ]
