# Generated by Django 5.2.8 on 2025-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_coursequiz_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateField(blank=True, null=True),
        ),
    ]
