# Generated by Django 5.2.5 on 2025-11-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customuser_cover_photo_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_active',
        ),
    ]
