# Generated by Django 5.2.8 on 2025-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateField(blank=True, null=True),
        ),
    ]
