# Generated by Django 5.2.8 on 2026-01-03 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import uuid

def populate_certificate_uuid(apps, schema_editor):
    Certificate = apps.get_model('core', 'Certificate')
    for cert in Certificate.objects.filter(certificate_id__isnull=True):
        cert.certificate_id = uuid.uuid4()
        cert.save(update_fields=['certificate_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hackinglab_userlabprogress'),
    ]

    operations = [
    migrations.AddField(
        model_name='certificate',
        name='certificate_id',
        field=models.UUIDField(null=True, blank=True),
    ),

    migrations.RunPython(populate_certificate_uuid),

    migrations.AlterField(
        model_name='certificate',
        name='certificate_id',
        field=models.UUIDField(default=uuid.uuid4, unique=True),
    ),

    migrations.AddField(
        model_name='certificate',
        name='public',
        field=models.BooleanField(default=True),
    ),

    migrations.AddField(
        model_name='usercourseprogress',
        name='current_lesson',
        field=models.ForeignKey(
            blank=True,
            null=True,
            on_delete=models.SET_NULL,
            related_name='+',
            to='core.lesson',
        ),
    ),

  migrations.CreateModel(
    name='CourseQuizQuestion',
    fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('question', models.TextField()),
        ('order', models.PositiveIntegerField(default=0)),
        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.course')),
    ],
    options={
        'ordering': ['order'],
    },
),


   migrations.CreateModel(
    name='CourseQuizOption',
    fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('text', models.CharField(max_length=255)),
        ('is_correct', models.BooleanField(default=False)),
        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.coursequizquestion')),
    ],
),

migrations.CreateModel(
    name='CourseQuizAttempt',
    fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('score', models.IntegerField()),
        ('attempt_no', models.PositiveIntegerField()),
        ('passed', models.BooleanField(default=False)),
        ('attempted_at', models.DateTimeField(auto_now_add=True)),
        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
    ],
    options={
        'ordering': ['-attempt_no'],
        'unique_together': {('user', 'course', 'attempt_no')},
    },
),

]
