# Generated by Django 5.2.8 on 2026-01-03 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_certificate_certificate_id_certificate_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequizattempt',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempt', to='core.certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
