# Generated by Django 5.2.8 on 2026-01-04 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_coursequizattempt_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.RemoveField(
            model_name='coursequizattempt',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'related_course')},
        ),
    ]
