# Generated by Django 5.2.8 on 2026-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Markdown or HTML supported'),
        ),
    ]
