# Generated by Django 5.2.8 on 2026-01-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_lesson_options_remove_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
